#include <stdio.h>
#include <windows.h>

void picture_move(int time);

int main()
{
    picture_move(100);
    return 0;
}
void picture_move(int time)
{
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                                            $$_$$");
    printf("\nX                                          $(.)$(.)$$$");
    printf("\nX                                       $$$$_____$$___$");
    printf("\nX                                      $_______________$");
    printf("\nX                                      $__________$_____$");
    printf("\nX                                       $$_______$$$$___$");
    printf("\nX                               $    $$$_$$$___$$   $___$");
    printf("\nX                                $  $$       $$$    $___$");
    printf("\nX                              $$$$$              $$___$");
    printf("\nX                                          $$$$$$$____$$");
    printf("\nX                                        $$$__________$$");
    printf("\nX                                      $$__________$$$$");
    printf("\nX                                     $_______$$$$$$$");
    printf("\nX                                   $_______$              ");
    printf("\nX                                  $_______$$            $$");
    printf("\nX                                  $_______$$$        $$$$__");
    printf("\nX                                  $________$$$     $$______");
    printf("\nX                                  $________$$$$$$$$$$$$___");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                                          $$_$$");
    printf("\nX                                        $(.)$(.)$$$");
    printf("\nX                                     $$$$_____$$___$");
    printf("\nX                                    $_______________$");
    printf("\nX                                    $__________$_____$");
    printf("\nX                                     $$_______$$$$___$");
    printf("\nX                             $    $$$_$$$___$$   $___$");
    printf("\nX                              $  $$       $$$    $___$");
    printf("\nX                            $$$$$              $$___$");
    printf("\nX                                        $$$$$$$____$$");
    printf("\nX                                      $$$__________$$");
    printf("\nX                                    $$__________$$$$");
    printf("\nX                                   $_______$$$$$$$");
    printf("\nX                                 $_______$              $$");
    printf("\nX                                $_______$$            $$$$");
    printf("\nX                                $_______$$$        $$$$___$");
    printf("\nX                                $________$$$     $$_______$");
    printf("\nX                                $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                                        $$_$$");
    printf("\nX                                      $(.)$(.)$$$");
    printf("\nX                                   $$$$_____$$___$");
    printf("\nX                                  $_______________$");
    printf("\nX                                  $__________$_____$");
    printf("\nX                                   $$_______$$$$___$");
    printf("\nX                           $    $$$_$$$___$$   $___$");
    printf("\nX                            $  $$       $$$    $___$");
    printf("\nX                          $$$$$              $$___$");
    printf("\nX                                      $$$$$$$____$$");
    printf("\nX                                    $$$__________$$");
    printf("\nX                                  $$__________$$$$");
    printf("\nX                                 $_______$$$$$$$");
    printf("\nX                               $_______$              $$");
    printf("\nX                              $_______$$            $$$$");
    printf("\nX                              $_______$$$        $$$$___$");
    printf("\nX                              $________$$$     $$_______$");
    printf("\nX                              $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                                      $$_$$");
    printf("\nX                                    $(.)$(.)$$$");
    printf("\nX                                 $$$$_____$$___$");
    printf("\nX                                $_______________$");
    printf("\nX                                $__________$_____$");
    printf("\nX                                 $$_______$$$$___$");
    printf("\nX                         $    $$$_$$$___$$   $___$");
    printf("\nX                          $  $$       $$$    $___$");
    printf("\nX                        $$$$$              $$___$");
    printf("\nX                                    $$$$$$$____$$");
    printf("\nX                                  $$$__________$$");
    printf("\nX                                $$__________$$$$");
    printf("\nX                               $_______$$$$$$$");
    printf("\nX                             $_______$              $$");
    printf("\nX                            $_______$$            $$$$");
    printf("\nX                            $_______$$$        $$$$___$");
    printf("\nX                            $________$$$     $$_______$");
    printf("\nX                            $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                                    $$_$$");
    printf("\nX                                  $(.)$(.)$$$");
    printf("\nX                               $$$$_____$$___$");
    printf("\nX                              $_______________$");
    printf("\nX                              $__________$_____$");
    printf("\nX                               $$_______$$$$___$");
    printf("\nX                       $    $$$_$$$___$$   $___$");
    printf("\nX                        $  $$       $$$    $___$");
    printf("\nX                      $$$$$              $$___$");
    printf("\nX                                  $$$$$$$____$$");
    printf("\nX                                $$$__________$$");
    printf("\nX                              $$__________$$$$");
    printf("\nX                             $_______$$$$$$$");
    printf("\nX                           $_______$              $$");
    printf("\nX                          $_______$$            $$$$");
    printf("\nX                          $_______$$$        $$$$___$");
    printf("\nX                          $________$$$     $$_______$");
    printf("\nX                          $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                                  $$_$$");
    printf("\nX                                $(.)$(.)$$$");
    printf("\nX                             $$$$_____$$___$");
    printf("\nX                            $_______________$");
    printf("\nX                            $__________$_____$");
    printf("\nX                             $$_______$$$$___$");
    printf("\nX                     $    $$$_$$$___$$   $___$");
    printf("\nX                      $  $$       $$$    $___$");
    printf("\nX                    $$$$$              $$___$");
    printf("\nX                                $$$$$$$____$$");
    printf("\nX                              $$$__________$$");
    printf("\nX                            $$__________$$$$");
    printf("\nX                           $_______$$$$$$$");
    printf("\nX                         $_______$              $$");
    printf("\nX                        $_______$$            $$$$");
    printf("\nX                        $_______$$$        $$$$___$");
    printf("\nX                        $________$$$     $$_______$");
    printf("\nX                        $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                                $$_$$");
    printf("\nX                              $(.)$(.)$$$");
    printf("\nX                           $$$$_____$$___$");
    printf("\nX                          $_______________$");
    printf("\nX                          $__________$_____$");
    printf("\nX                           $$_______$$$$___$");
    printf("\nX                   $    $$$_$$$___$$   $___$");
    printf("\nX                    $  $$       $$$    $___$");
    printf("\nX                  $$$$$              $$___$");
    printf("\nX                              $$$$$$$____$$");
    printf("\nX                            $$$__________$$");
    printf("\nX                          $$__________$$$$");
    printf("\nX                         $_______$$$$$$$");
    printf("\nX                       $_______$              $$");
    printf("\nX                      $_______$$            $$$$");
    printf("\nX                      $_______$$$        $$$$___$");
    printf("\nX                      $________$$$     $$_______$");
    printf("\nX                      $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                              $$_$$");
    printf("\nX                            $(.)$(.)$$$");
    printf("\nX                         $$$$_____$$___$");
    printf("\nX                        $_______________$");
    printf("\nX                        $__________$_____$");
    printf("\nX                         $$_______$$$$___$");
    printf("\nX                 $    $$$_$$$___$$   $___$");
    printf("\nX                  $  $$       $$$    $___$");
    printf("\nX                $$$$$              $$___$");
    printf("\nX                            $$$$$$$____$$");
    printf("\nX                          $$$__________$$");
    printf("\nX                        $$__________$$$$");
    printf("\nX                       $_______$$$$$$$");
    printf("\nX                     $_______$              $$");
    printf("\nX                    $_______$$            $$$$");
    printf("\nX                    $_______$$$        $$$$___$");
    printf("\nX                    $________$$$     $$_______$");
    printf("\nX                    $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                            $$_$$");
    printf("\nX                          $(.)$(.)$$$");
    printf("\nX                       $$$$_____$$___$");
    printf("\nX                      $_______________$");
    printf("\nX                      $__________$_____$");
    printf("\nX                       $$_______$$$$___$");
    printf("\nX               $    $$$_$$$___$$   $___$");
    printf("\nX                $  $$       $$$    $___$");
    printf("\nX              $$$$$              $$___$");
    printf("\nX                          $$$$$$$____$$");
    printf("\nX                        $$$__________$$");
    printf("\nX                      $$__________$$$$");
    printf("\nX                     $_______$$$$$$$");
    printf("\nX                   $_______$              $$");
    printf("\nX                  $_______$$            $$$$");
    printf("\nX                  $_______$$$        $$$$___$");
    printf("\nX                  $________$$$     $$_______$");
    printf("\nX                  $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                          $$_$$");
    printf("\nX                        $(.)$(.)$$$");
    printf("\nX                     $$$$_____$$___$");
    printf("\nX                    $_______________$");
    printf("\nX                    $__________$_____$");
    printf("\nX                     $$_______$$$$___$");
    printf("\nX             $    $$$_$$$___$$   $___$");
    printf("\nX              $  $$       $$$    $___$");
    printf("\nX            $$$$$              $$___$");
    printf("\nX                        $$$$$$$____$$");
    printf("\nX                      $$$__________$$");
    printf("\nX                    $$__________$$$$");
    printf("\nX                   $_______$$$$$$$");
    printf("\nX                 $_______$              $$");
    printf("\nX                $_______$$            $$$$");
    printf("\nX                $_______$$$        $$$$___$");
    printf("\nX                $________$$$     $$_______$");
    printf("\nX                $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                        $$_$$");
    printf("\nX                      $(.)$(.)$$$");
    printf("\nX                   $$$$_____$$___$");
    printf("\nX                  $_______________$");
    printf("\nX                  $__________$_____$");
    printf("\nX                   $$_______$$$$___$");
    printf("\nX           $    $$$_$$$___$$   $___$");
    printf("\nX            $  $$       $$$    $___$");
    printf("\nX          $$$$$              $$___$");
    printf("\nX                      $$$$$$$____$$");
    printf("\nX                    $$$__________$$");
    printf("\nX                  $$__________$$$$");
    printf("\nX                 $_______$$$$$$$");
    printf("\nX               $_______$              $$");
    printf("\nX              $_______$$            $$$$");
    printf("\nX              $_______$$$        $$$$___$");
    printf("\nX              $________$$$     $$_______$");
    printf("\nX              $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                      $$_$$");
    printf("\nX                    $(.)$(.)$$$");
    printf("\nX                 $$$$_____$$___$");
    printf("\nX                $_______________$");
    printf("\nX                $__________$_____$");
    printf("\nX                 $$_______$$$$___$");
    printf("\nX         $    $$$_$$$___$$   $___$");
    printf("\nX          $  $$       $$$    $___$");
    printf("\nX        $$$$$              $$___$");
    printf("\nX                    $$$$$$$____$$");
    printf("\nX                  $$$__________$$");
    printf("\nX                $$__________$$$$");
    printf("\nX               $_______$$$$$$$");
    printf("\nX             $_______$              $$");
    printf("\nX            $_______$$            $$$$");
    printf("\nX            $_______$$$        $$$$___$");
    printf("\nX            $________$$$     $$_______$");
    printf("\nX            $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                    $$_$$");
    printf("\nX                  $(.)$(.)$$$");
    printf("\nX               $$$$_____$$___$");
    printf("\nX              $_______________$");
    printf("\nX              $__________$_____$");
    printf("\nX               $$_______$$$$___$");
    printf("\nX       $    $$$_$$$___$$   $___$");
    printf("\nX        $  $$       $$$    $___$");
    printf("\nX      $$$$$              $$___$");
    printf("\nX                  $$$$$$$____$$");
    printf("\nX                $$$__________$$");
    printf("\nX              $$__________$$$$");
    printf("\nX             $_______$$$$$$$");
    printf("\nX           $_______$              $$");
    printf("\nX          $_______$$            $$$$");
    printf("\nX          $_______$$$        $$$$___$");
    printf("\nX          $________$$$     $$_______$");
    printf("\nX          $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                  $$_$$");
    printf("\nX                $(.)$(.)$$$");
    printf("\nX             $$$$_____$$___$");
    printf("\nX            $_______________$");
    printf("\nX            $__________$_____$");
    printf("\nX             $$_______$$$$___$");
    printf("\nX     $    $$$_$$$___$$   $___$");
    printf("\nX      $  $$       $$$    $___$");
    printf("\nX    $$$$$              $$___$");
    printf("\nX                $$$$$$$____$$");
    printf("\nX              $$$__________$$");
    printf("\nX            $$__________$$$$");
    printf("\nX           $_______$$$$$$$");
    printf("\nX         $_______$              $$");
    printf("\nX        $_______$$            $$$$");
    printf("\nX        $_______$$$        $$$$___$");
    printf("\nX        $________$$$     $$_______$");
    printf("\nX        $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX                $$_$$");
    printf("\nX              $(.)$(.)$$$");
    printf("\nX           $$$$_____$$___$");
    printf("\nX          $_______________$");
    printf("\nX          $__________$_____$");
    printf("\nX           $$_______$$$$___$");
    printf("\nX   $    $$$_$$$___$$   $___$");
    printf("\nX    $  $$       $$$    $___$");
    printf("\nX  $$$$$              $$___$");
    printf("\nX              $$$$$$$____$$");
    printf("\nX            $$$__________$$");
    printf("\nX          $$__________$$$$");
    printf("\nX         $_______$$$$$$$");
    printf("\nX       $_______$              $$");
    printf("\nX      $_______$$            $$$$");
    printf("\nX      $_______$$$        $$$$___$");
    printf("\nX      $________$$$     $$_______$");
    printf("\nX      $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX              $$_$$");
    printf("\nX            $(.)$(.)$$$");
    printf("\nX         $$$$_____$$___$");
    printf("\nX        $_______________$");
    printf("\nX        $__________$_____$");
    printf("\nX         $$_______$$$$___$");
    printf("\nX $    $$$_$$$___$$   $___$");
    printf("\nX  $  $$       $$$    $___$");
    printf("\nX$$$$$              $$___$");
    printf("\nX            $$$$$$$____$$");
    printf("\nX          $$$__________$$");
    printf("\nX        $$__________$$$$");
    printf("\nX       $_______$$$$$$$");
    printf("\nX     $_______$              $$");
    printf("\nX    $_______$$            $$$$");
    printf("\nX    $_______$$$        $$$$___$");
    printf("\nX    $________$$$     $$_______$");
    printf("\nX    $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX            $$_$$");
    printf("\nX          $(.)$(.)$$$");
    printf("\nX       $$$$_____$$___$");
    printf("\nX      $_______________$");
    printf("\nX      $__________$_____$");
    printf("\nX       $$_______$$$$___$");
    printf("\nX    $$$_$$$___$$   $___$");
    printf("\nX$  $$       $$$    $___$");
    printf("\nX$$$              $$___$");
    printf("\nX          $$$$$$$____$$");
    printf("\nX        $$$__________$$");
    printf("\nX      $$__________$$$$");
    printf("\nX     $_______$$$$$$$");
    printf("\nX   $_______$              $$");
    printf("\nX  $_______$$            $$$$");
    printf("\nX  $_______$$$        $$$$___$");
    printf("\nX  $________$$$     $$_______$");
    printf("\nX  $________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX          $$_$$");
    printf("\nX        $(.)$(.)$$$");
    printf("\nX     $$$$_____$$___$");
    printf("\nX    $_______________$");
    printf("\nX    $__________$_____$");
    printf("\nX     $$_______$$$$___$");
    printf("\nX  $$$_$$$___$$   $___$");
    printf("\nX $$       $$$    $___$");
    printf("\nX$              $$___$");
    printf("\nX        $$$$$$$____$$");
    printf("\nX      $$$__________$$");
    printf("\nX    $$__________$$$$");
    printf("\nX   $_______$$$$$$$");
    printf("\nX $_______$              $$");
    printf("\nX$_______$$            $$$$");
    printf("\nX$_______$$$        $$$$___$");
    printf("\nX$________$$$     $$_______$");
    printf("\nX$________$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX        $$_$$");
    printf("\nX      $(.)$(.)$$$");
    printf("\nX   $$$$_____$$___$");
    printf("\nX  $_______________$");
    printf("\nX  $__________$_____$");
    printf("\nX   $$_______$$$$___$");
    printf("\nX$$$_$$$___$$   $___$");
    printf("\nX$       $$$    $___$");
    printf("\nX             $$___$");
    printf("\nX      $$$$$$$____$$");
    printf("\nX    $$$__________$$");
    printf("\nX  $$__________$$$$");
    printf("\nX $_______$$$$$$$");
    printf("\nX_______$              $$");
    printf("\nX______$$            $$$$");
    printf("\nX______$$$        $$$$___$");
    printf("\nX_______$$$     $$_______$");
    printf("\nX_______$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX      $$_$$");
    printf("\nX    $(.)$(.)$$$");
    printf("\nX $$$$_____$$___$");
    printf("\nX$_______________$");
    printf("\nX$__________$_____$");
    printf("\nX $$_______$$$$___$");
    printf("\nX$_$$$___$$   $___$");
    printf("\nX      $$$    $___$");
    printf("\nX           $$___$");
    printf("\nX    $$$$$$$____$$");
    printf("\nX  $$$__________$$");
    printf("\nX$$__________$$$$");
    printf("\nX_______$$$$$$$");
    printf("\nX_____$              $$");
    printf("\nX____$$            $$$$");
    printf("\nX____$$$        $$$$___$");
    printf("\nX_____$$$     $$_______$");
    printf("\nX_____$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX    $$_$$");
    printf("\nX  $(.)$(.)$$$");
    printf("\nX$$$_____$$___$");
    printf("\nX______________$");
    printf("\nX_________$_____$");
    printf("\nX$_______$$$$___$");
    printf("\nX$$$___$$   $___$");
    printf("\nX    $$$    $___$");
    printf("\nX         $$___$");
    printf("\nX  $$$$$$$____$$");
    printf("\nX$$$__________$$");
    printf("\nX__________$$$$");
    printf("\nX_____$$$$$$$");
    printf("\nX___$              $$");
    printf("\nX__$$            $$$$");
    printf("\nX__$$$        $$$$___$");
    printf("\nX___$$$     $$_______$");
    printf("\nX___$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX  $$_$$");
    printf("\nX$(.)$(.)$$$");
    printf("\nX$_____$$___$");
    printf("\nX____________$");
    printf("\nX_______$_____$");
    printf("\nX______$$$$___$");
    printf("\nX$___$$   $___$");
    printf("\nX  $$$    $___$");
    printf("\nX       $$___$");
    printf("\nX$$$$$$$____$$");
    printf("\nX$__________$$");
    printf("\nX________$$$$");
    printf("\nX___$$$$$$$");
    printf("\nX_$              $$");
    printf("\nX$$            $$$$");
    printf("\nX$$$        $$$$___$");
    printf("\nX_$$$     $$_______$");
    printf("\nX_$$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX$$_$$");
    printf("\nX.)$(.)$$$");
    printf("\nX____$$___$");
    printf("\nX__________$");
    printf("\nX_____$_____$");
    printf("\nX____$$$$___$");
    printf("\nX__$$   $___$");
    printf("\nX$$$    $___$");
    printf("\nX     $$___$");
    printf("\nX$$$$$____$$");
    printf("\nX_________$$");
    printf("\nX______$$$$");
    printf("\nX_$$$$$$$");
    printf("\nX              $$");
    printf("\nX            $$$$");
    printf("\nX$        $$$$___$");
    printf("\nX$$     $$_______$");
    printf("\nX$$$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX_$$");
    printf("\nX$(.)$$$");
    printf("\nX__$$___$");
    printf("\nX________$");
    printf("\nX___$_____$");
    printf("\nX__$$$$___$");
    printf("\nX$$   $___$");
    printf("\nX$    $___$");
    printf("\nX   $$___$");
    printf("\nX$$$____$$");
    printf("\nX_______$$");
    printf("\nX____$$$$");
    printf("\nX$$$$$$");
    printf("\nX            $$");
    printf("\nX          $$$$");
    printf("\nX       $$$$___$");
    printf("\nX     $$_______$");
    printf("\nX$$$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX$");
    printf("\nX.)$$$");
    printf("\nX$$___$");
    printf("\nX______$");
    printf("\nX_$_____$");
    printf("\nX$$$$___$");
    printf("\nX   $___$");
    printf("\nX   $___$");
    printf("\nX $$___$");
    printf("\nX$____$$");
    printf("\nX_____$$");
    printf("\nX__$$$$");
    printf("\nX$$$$");
    printf("\nX          $$");
    printf("\nX        $$$$");
    printf("\nX     $$$$___$");
    printf("\nX   $$_______$");
    printf("\nX$$$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX");
    printf("\nX$$$");
    printf("\nX___$");
    printf("\nX____$");
    printf("\nX_____$");
    printf("\nX$$___$");
    printf("\nX $___$");
    printf("\nX $___$");
    printf("\nX$___$");
    printf("\nX___$$");
    printf("\nX___$$");
    printf("\nX$$$$");
    printf("\nX$$");
    printf("\nX        $$");
    printf("\nX      $$$$");
    printf("\nX   $$$$___$");
    printf("\nX $$_______$");
    printf("\nX$$$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX");
    printf("\nX$");
    printf("\nX_$");
    printf("\nX__$");
    printf("\nX___$");
    printf("\nX___$");
    printf("\nX___$");
    printf("\nX___$");
    printf("\nX__$");
    printf("\nX_$$");
    printf("\nX_$$");
    printf("\nX$$");
    printf("\nX");
    printf("\nX      $$");
    printf("\nX    $$$$");
    printf("\nX $$$$___$");
    printf("\nX$_______$");
    printf("\nX$$$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX$");
    printf("\nX_$");
    printf("\nX_$");
    printf("\nX_$");
    printf("\nX_$");
    printf("\nX$");
    printf("\nX$");
    printf("\nX$");
    printf("\nX");
    printf("\nX");
    printf("\nX    $$");
    printf("\nX  $$$$");
    printf("\nX$$$___$");
    printf("\nX______$");
    printf("\nX$____$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX  $$");
    printf("\nX$$$$");
    printf("\nX$___$");
    printf("\nX____$");
    printf("\nX___$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX$$");
    printf("\nX$$");
    printf("\nX__$");
    printf("\nX__$");
    printf("\nX_$");
    Sleep(time);
    system("cls");
    printf("X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    printf("\nX");
    Sleep(time);
    system("cls");
}