{
 "title": "Digital Twin",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Digital Twin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Speed [%]",
   "type": "timeseries",
   "description": "Current Speed Setting",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "[https://example.com/ids/aas/3192_3172_0122_3826]/[TechnicalData]/[SpeedOfProcessing]",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Temperature [°C]",
   "type": "timeseries",
   "description": "Current temperature of the machine",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "[https://example.com/ids/aas/3192_3172_0122_3826]/[TechnicalData]/[TemperatureOfMachine]",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Produced Items",
   "type": "timeseries",
   "description": "Number of produced items",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "target": "[https://example.com/ids/aas/3192_3172_0122_3826]/[TechnicalData]/[NumberOfProducedItems]",
     "type": "timeserie"
    }
   ]
  }
 ]
}